spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankmockdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:dev-secret-please-change}
  expiration: 3600000 # 1h in ms
logging:
  level:
    org.hibernate.SQL: warn
